services:
  pomacea:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: pomacea-reporter
    ports:
      - "9000:9000"
    restart: unless-stopped
    volumes:
      - ./data:/data
